spring.application.name=my-wiki

spring.config.import=optional:classpath:application-local.properties

# 아래 주석 줄들의 주석을 해제한 뒤, { }를 지우고 그 자리에 본인의 데이터베이스 계정 url, 계정명, 비밀번호 등을 입력하세요.
# spring.datasource.url={YOUR_DB_URL}
# spring.datasource.username={YOUR_DB_USER_NAME}
# spring.datasource.password={YOUR_DB_PASSWORD}
# spring.datasource.driver-class-name={YOUR_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true