spring.application.name=my-wiki

# ?? ????, ??? ???? { } ??? ?? ? ??? ???? ?? ????
# spring.datasource.url={YOUR_DB_URL}
# spring.datasource.username={YOUR_DB_USER_NAME}
# spring.datasource.password={YOUR_DB_PASSWORD}
# spring.datasource.driver-class-name={YOUR_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true